services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qr_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
