[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "litestar[standard]>=2.15.1",
    "pillow>=11.1.0",
    "qrcode>=8.0",
]
